name: CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: 'datagaze'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.0'

      - name: Install dependencies
        run: npm install

      - name: Build and Test
        run: npm run build

      - name: Deploy
        run:  cp -a ~/datagaze/actions-runner/_work/datagaze-task/datagaze-task/dist/. /var/www/datagaze.educon.uz/html

